services:
  - type: web
    name: entrega-facil
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: entrega-facil-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true

databases:
  - name: entrega-facil-db
    databaseName: entrega_facil
    plan: free